# Generated by Django 5.1.2 on 2025-02-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('telephone', 'Telephone'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('file', 'File')], max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('max_characters', models.IntegerField(blank=True, null=True)),
                ('min_characters', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
