# Generated by Django 5.1.2 on 2025-02-16 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inputfield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZakatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidites', models.FloatField()),
                ('stocks', models.FloatField()),
                ('investissements', models.FloatField()),
                ('bien_location', models.FloatField()),
                ('creances_clients', models.FloatField()),
                ('bien_usage_interne', models.FloatField()),
                ('fonds_non_dispo', models.FloatField()),
                ('stocks_invendable', models.FloatField()),
                ('zakat_amount', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
