# Generated by Django 5.2 on 2025-04-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_zakathistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waqfproject',
            name='name',
            field=models.CharField(default='Unnamed Project', max_length=255, unique=True),
        ),
    ]
