# Generated by Django 5.1.2 on 2025-02-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_zakathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakathistory',
            name='nisab',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
