# Generated by Django 5.1.2 on 2025-02-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_zakathistory_nisab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakathistory',
            name='zakat_amount',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
