# Generated by Django 5.1.2 on 2025-02-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_zakathistory_zakat_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaqfProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('introduction', models.TextField()),
                ('background', models.TextField()),
                ('objectives', models.TextField()),
                ('key_stages', models.TextField()),
                ('expected_outcomes', models.TextField()),
                ('challenges_solutions', models.TextField()),
                ('required_resources', models.TextField()),
                ('timeline', models.TextField()),
                ('tools_technologies', models.TextField()),
                ('team_members', models.TextField()),
                ('partners_supporters', models.TextField()),
                ('conclusion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
