# Generated by Django 5.1.2 on 2025-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_waqfproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='waqfproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waqf_images/'),
        ),
    ]
