# Generated by Django 5.1.7 on 2025-03-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_otpcode_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wakf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('timeline', models.DateField()),
                ('partners', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='background',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='challenges_solutions',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='expected_outcomes',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='image',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='key_stages',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='partners_supporters',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='required_resources',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='team_members',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='timeline',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='tools_technologies',
        ),
        migrations.RemoveField(
            model_name='waqfproject',
            name='updated_at',
        ),
    ]
