# Generated by Django 5.1.7 on 2025-03-26 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_wakf_remove_waqfproject_background_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wakf',
        ),
        migrations.AddField(
            model_name='waqfproject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='waqfproject',
            name='domain',
            field=models.CharField(default='General', max_length=255),
        ),
        migrations.AddField(
            model_name='waqfproject',
            name='name',
            field=models.CharField(default='Unnamed Project', max_length=255),
        ),
        migrations.AddField(
            model_name='waqfproject',
            name='objectives',
            field=models.TextField(default='No objectives specified'),
        ),
        migrations.AddField(
            model_name='waqfproject',
            name='partners',
            field=models.TextField(default='No partners specified'),
        ),
        migrations.AddField(
            model_name='waqfproject',
            name='timeline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='waqfproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
