# Generated by Django 5.1.7 on 2025-03-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_wakf_waqfproject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waqfproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='waqf_images/'),
        ),
    ]
