# Generated by Django 5.1.7 on 2025-03-26 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_waqfproject_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waqfproject',
            name='timeline',
        ),
    ]
